defaults: &defaults
  working_directory: ~/project
  docker:
    - image: 'nfour/circleci-node:9'


version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run: yarn preversion


  deploy:
    <<: *defaults

    filters:
      tags:
        only: /.+/

    steps:
      - run: pwd
      - run: yarn release

workflows:
  version: 2
  buildAndDeploy:
    jobs:
      - build

